kind: pipeline
type: docker
name: default

steps:
- name: publish
  image: plugins/ecr
  region: us-east-1
  access_key: $AWS_ACCESS_KEY_ID  
  secret_key: $AWS_SECRET_ACCESS_KEY
  registry: $AWS_ECR_PREFIX.dkr.ecr.us-east-1.amazonaws.com
  repo: teste
  force_tag: true
  create_repository: true
  environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_ECR_PREFIX:
        from_secret: AWS_ECR_PREFIX
