kind: pipeline
type: docker
name: default

steps:
- name: constroi app
  image: plugins/ecr
  settings:
    access_key:
        from_secret: AWS_ACCESS_KEY_ID
    secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
    registry: 933375035704.dkr.ecr.us-east-1.amazonaws.com
    repo: 933375035704.dkr.ecr.us-east-1.amazonaws.com/getip-drone
    region: us-east-1
    debug: true
  #environment:
      #AWS_ECR_PREFIX:
        #from_secret: AWS_ECR_PREFIX

- name: executa terraform
  image: hashicorp/terraform:1.0.0
  commands:
  - terraform init 
  - terraform workspace select dev || terraform workspace new dev
  - terraform plan
  - terraform apply -auto-approve
  - terraform output -raw ip_address >> ip_address
  environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:  
        from_secret: AWS_SECRET_ACCESS_KEY

- name: deploy 
  image: ubuntu
  commands:
  - whoami
  - apt-get update
  - apt-get install ssh
  - ls -larth
  - export ip=`cat ip_address`
  - echo $ip
  - echo ${SSH_AWS_EC2} >> aws_ec2.pub
  - cat aws_ec2.pub
  - ssh -i aws_ec2.pub ubuntu@$ip
  - touch teste
  environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:  
        from_secret: AWS_SECRET_ACCESS_KEY
      SSH_AWS_EC2:
        from_secret: SSH_AWS_EC2

