kind: pipeline
type: docker
name: default

steps:
- name: publish
  image: plugins/ecr
  settings:
    access_key:
        from_secret: AWS_ACCESS_KEY_ID
    secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
    registry: $AWS_ECR_PREFIX.dkr.ecr.us-east-1.amazonaws.com
    repo: $AWS_ECR_PREFIX.dkr.ecr.us-east-1.amazonaws.com/getip-drone
    region: us-east-1
  environment:
      AWS_ECR_PREFIX:
        from_secret: AWS_ECR_PREFIX
