kind: pipeline
type: docker
name: default

steps:
- name: publish
  image: plugins/ecr
  settings:
    registry: $AWS_ECR_PREFIX.dkr.ecr.us-east-1.amazonaws.com
    repo: getip-drone
    create_repository: true
    access_key:
        from_secret: AWS_ACCESS_KEY_ID
    secret_key:
        from_secret: AWS_SECRET_ACCESS_KEYe
  environment:
      AWS_ECR_PREFIX:
        from_secret: AWS_ECR_PREFIX
