kind: pipeline
type: docker
name: default

steps:
- name: constroi app
  image: plugins/ecr
  settings:
    access_key:
        from_secret: AWS_ACCESS_KEY_ID
    secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
    registry: 933375035704.dkr.ecr.us-east-1.amazonaws.com
    repo: 933375035704.dkr.ecr.us-east-1.amazonaws.com/getip-drone
    region: us-east-1
    debug: true
  #environment:
      #AWS_ECR_PREFIX:
        #from_secret: AWS_ECR_PREFIX

- name: executa terraform
  image: hashicorp/terraform:1.0.0
  commands:
  - terraform init 
  - terraform workspace select dev || terraform workspace new dev
  - terraform plan
  - terraform apply -auto-approve
  - terraform output -raw ip_address >> ip_address
  environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:  
        from_secret: AWS_SECRET_ACCESS_KEY
        
- name: deployment
  image: appleboy/drone-ssh
  #commands:
  #- export ip=`cat ip_address`
  #- echo $ip
  settings:
    host: 100.26.210.122
    username: ubuntu
    port: 22
    key:
      from_secret: SSH_AWS_EC2
    script:
      - sudo aws ecr get-login-password | docker login --username AWS --password-stdin 933375035704.dkr.ecr.us-east-1.amazonaws.com/getip-drone
      #- sudo docker rm -f getipv2 || true
      - sudo docker run -d --name getipv2 -p 8090:8090 933375035704.dkr.ecr.us-east-1.amazonaws.com/getip-drone:latest
  environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:  
        from_secret: AWS_SECRET_ACCESS_KEY
      SSH_AWS_EC2:
        from_secret: SSH_AWS_EC2
